/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author José Luis
 */
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.*;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
public class Interfaz_grafico extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_grafico
     */
    JFreeChart Grafica_barra;
    JFreeChart Grafica_pastel;
    String tipo[]={"Discapacitados","Adulto mayor","Mujer embarazada", "Cliente corporativo","Cliente regular"};
    
    public Interfaz_grafico() {
        initComponents();
        setTitle("Reportes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Reportes:cantidad de clientes por tipo:");

        jButton1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton1.setText("Gráfico de Barras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton2.setText("Gráfico Pastel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Reportes:cantidad de clientes por Hora y Día.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este es el metodo que le devuelve el arreglo con la informacion de todos los clientes
    //String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
    //Este devuelve la cantidad de clientes registrados
    //int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         DefaultCategoryDataset datos_tipo= new DefaultCategoryDataset();
        
        datos_tipo.addValue(5,"tipo", tipo[0]);
        datos_tipo.addValue(10,"tipo",tipo[1]);
        datos_tipo.addValue(15,"tipo",tipo[2]);
        datos_tipo.addValue(20,"tipo",tipo[3]);
        datos_tipo.addValue(25,"tipo",tipo[4]);
   
   
        Grafica_barra = ChartFactory.createBarChart("Reportes", "tipos","Cantidad de clientes", datos_tipo, PlotOrientation.VERTICAL,true,true,false);
   
        //se crea un panel y se agreaga la gráfica
        ChartPanel panel= new ChartPanel(Grafica_barra);
        // se crea un nuevo frame
        JFrame vent=new JFrame("grafica de barras");
        //se agrega al panel la nueva ventana
        vent.getContentPane().add(panel);
        //se resetea la nueva ventana
        vent.pack();
        // se hace visible la ventana
        vent.setVisible(true);
        // se establce la acción hara ventana cuando
        //se presione el boton de cerrar
        vent.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        vent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         DefaultPieDataset datos = new DefaultPieDataset();

        datos.setValue(tipo[0], 10);
        datos.setValue(tipo[1], 20);
        datos.setValue(tipo[2], 30);
        datos.setValue(tipo[3], 40);
        datos.setValue(tipo[4], 50);
      
        Grafica_pastel = ChartFactory.createPieChart("Reportes",datos,true,true,false);    
        //se crea un panel y se agreaga la gráfica
        ChartPanel panel= new ChartPanel(Grafica_pastel);
        // se crea un nuevo frame
        JFrame vent=new JFrame("grafica de pastel");
        //se agrega al panel la nueva ventana
        vent.getContentPane().add(panel);
        //se resetea la nueva ventana
        vent.pack();
        // se hace visible la ventana
        vent.setVisible(true);
        // se establce la acción hara ventana cuando
        //se presione el boton de cerrar
        vent.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        vent.setVisible(true);   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_grafico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
