
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Creacion de la tabla con la informacion de los clientes
 * @author jhonson
 */
public class Interfaz_Tabla extends javax.swing.JFrame {
    DefaultTableModel Modelo;
    String Datos [][]={};
    String Columnas []={"Nombre", "Tipo","Correo","Fecha","Hora"};
    

    /**
     * Creates new form Interfaz_Principal
     */
    public Interfaz_Tabla() {
        initComponents();
        Modelo = new DefaultTableModel(Datos, Columnas);
        jTable1.setModel(Modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("URW Palladio L", 1, 24)); // NOI18N
        jLabel1.setText("Lista de clientes");

        jButton3.setText("Ordenar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Nombre", "Tipo","Correo","Fecha","Hora"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccion de orden");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Filtrar por fecha");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton3)))
                        .addGap(0, 238, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Vacia la tabla de los clientes
     */
    public void LimpiarTabla(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        for (int i=0; i<Contador;i++){
            Modelo.removeRow(0);
        }
    }
    /**
     * Metodo para elegir el ordenaiento de la tabla
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if("Nombre".equals((String)jComboBox1.getSelectedItem())){
            Ordenar_por_nombre();
        }
        if("Correo".equals((String)jComboBox1.getSelectedItem())){
            Ordenar_por_Correo();
        }
        if("Tipo".equals((String)jComboBox1.getSelectedItem())){
            Ordenar_por_Tipo();
        }
        if("Fecha".equals((String)jComboBox1.getSelectedItem())){
            Ordenar_por_Fecha();
        }
        if("Hora".equals((String)jComboBox1.getSelectedItem())){
            Ordenar_por_Hora();
        }
        
                
 
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Ordena la tabla por nombres
     */
    public void Ordenar_por_nombre(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=0;
        String [] ordenado;
        String [] Temporal=new String [Contador];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
                Temporal[i]=Datos_clientes[Contador2];
                Contador2=Contador2+5;  
            }
        ordenado=Ordenar.Ordenamiento(Temporal);
        LimpiarTabla();
        int contador5=0;
        for (int i=0; i<Contador;i++){
            while(!ordenado[i].equals(Datos_clientes[contador5])){
                contador5=contador5+5;
            }
            String [] Temporal2=new String [5];
            Temporal2[0]=Datos_clientes[contador5];
            Temporal2[1]=Datos_clientes[contador5+1];
            Temporal2[2]=Datos_clientes[contador5+2];
            Temporal2[3]=Datos_clientes[contador5+3];
            Temporal2[4]=Datos_clientes[contador5+4];
            Modelo.addRow(Temporal2);
            Datos_clientes[contador5]="";
            contador5=0;
            
            
         
        }
    }
    /**
     * Ordena la tabla por tipo de usuario
     */
    public void Ordenar_por_Tipo(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=1;
        String [] ordenado;
        String [] Temporal=new String [Contador];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
                Temporal[i]=Datos_clientes[Contador2];
                Contador2=Contador2+5;  
            }
        ordenado=Ordenar.Ordenamiento(Temporal);
        LimpiarTabla();
        int contador5=1;
        for (int i=0; i<Contador;i++){
            while(!ordenado[i].equals(Datos_clientes[contador5])){
                contador5=contador5+5;
            }
            String [] Temporal2=new String [5];
            Temporal2[0]=Datos_clientes[contador5-1];
            Temporal2[1]=Datos_clientes[contador5];
            Temporal2[2]=Datos_clientes[contador5+1];
            Temporal2[3]=Datos_clientes[contador5+2];
            Temporal2[4]=Datos_clientes[contador5+3];
            Modelo.addRow(Temporal2);
            Datos_clientes[contador5]="";
            contador5=1;
            
            
         
        }
    }
    /**
     * Ordena la tabla por fehca de ingreso
     */
    public void Ordenar_por_Fecha(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=3;
        String [] ordenado;
        String [] Temporal=new String [Contador];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
                Temporal[i]=Datos_clientes[Contador2];
                Contador2=Contador2+5;  
            }
        ordenado=Ordenar.Ordenamiento(Temporal);
        LimpiarTabla();
        int contador5=3;
        for (int i=0; i<Contador;i++){
            while(!ordenado[i].equals(Datos_clientes[contador5])){
                contador5=contador5+5;
            }
            String [] Temporal2=new String [5];
            Temporal2[0]=Datos_clientes[contador5-3];
            Temporal2[1]=Datos_clientes[contador5-2];
            Temporal2[2]=Datos_clientes[contador5-1];
            Temporal2[3]=Datos_clientes[contador5];
            Temporal2[4]=Datos_clientes[contador5+1];
            Modelo.addRow(Temporal2);
            Datos_clientes[contador5]="";
            contador5=3;
            
            
         
        }
    }
    /**
     * Ordena la tabla por hora de ingreso
     */
    public void Ordenar_por_Hora(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=4;
        String [] ordenado;
        String [] Temporal=new String [Contador];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
                Temporal[i]=Datos_clientes[Contador2];
                Contador2=Contador2+5;  
            }
        ordenado=Ordenar.Ordenamiento(Temporal);
        LimpiarTabla();
        int contador5=4;
        for (int i=0; i<Contador;i++){
            while(!ordenado[i].equals(Datos_clientes[contador5])){
                contador5=contador5+5;
            }
            String [] Temporal2=new String [5];
            Temporal2[0]=Datos_clientes[contador5-4];
            Temporal2[1]=Datos_clientes[contador5-3];
            Temporal2[2]=Datos_clientes[contador5-2];
            Temporal2[3]=Datos_clientes[contador5-1];
            Temporal2[4]=Datos_clientes[contador5];
            Modelo.addRow(Temporal2);
            Datos_clientes[contador5]="";
            contador5=4;
            
            
         
        }
    }
    /**
     * Ordena la tabla por correos  electronicos
     */
    public void Ordenar_por_Correo(){
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=2;
        String [] ordenado;
        String [] Temporal=new String [Contador];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
                Temporal[i]=Datos_clientes[Contador2];
                Contador2=Contador2+5;  
            }
        ordenado=Ordenar.Ordenamiento(Temporal);
        LimpiarTabla();
        int contador5=2;
        for (int i=0; i<Contador;i++){
            while(!ordenado[i].equals(Datos_clientes[contador5])){
                contador5=contador5+5;
            }
            String [] Temporal2=new String [5];
            Temporal2[0]=Datos_clientes[contador5-2];
            Temporal2[1]=Datos_clientes[contador5-1];
            Temporal2[2]=Datos_clientes[contador5];
            Temporal2[3]=Datos_clientes[contador5+1];
            Temporal2[4]=Datos_clientes[contador5+2];
            Modelo.addRow(Temporal2);
            Datos_clientes[contador5]="";
            contador5=2;
            
        }
    }
    /**
     * Ingresa los datos de los clientes a la tabla
     * @param evt 
     */
    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
         int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=0;
        int Contador4=0;
        String [] Temporal=new String [5];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
            while(Contador4<5){
                Temporal[Contador4]=Datos_clientes[Contador2];
                Contador4++;
                Contador2++;  
            }
            Modelo.addRow(Temporal);
            Contador4 = 0;
        }
    
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Filtra la tabla por fachas
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        LimpiarTabla();}
        catch(java.lang.ArrayIndexOutOfBoundsException e){
        }
        int Contador=Interfaz_Ingreso_informacion_usuario.DevolverContador();
        int Contador2=0;
        int Contador4=0;
        int Contador6=3;
        String [] Temporal=new String [5];
        String [] Datos_clientes=Interfaz_Ingreso_informacion_usuario.DevolverDatos();
        for (int i=0; i<Contador;i++){
            if(jTextField1.getText().equals(Datos_clientes[Contador6])){
            while(Contador4<5){
                Temporal[Contador4]=Datos_clientes[Contador2];
                Contador4++;
                Contador2++;  
            }
            Contador4 = 0;
            Modelo.addRow(Temporal);
            }
            else{
                Contador2=Contador2+5;
            }
            Contador6=Contador6+5; 
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
